# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - edited
  push:
    branches:
      - 'v*'
      - 'master'

jobs:
  build:
    runs-on: self-hosted
    permissions:
      contents: write

    env:
      DB_IP: ${{ secrets.DB_IP }}
      DB_NAME: ${{ secrets.DB_NAME }}
      USER_NAME: ${{ secrets.USER_NAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4.0.0

      - name: Set environment for jOOQ generation
        run: |
            echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
            echo "USER_NAME=${{ secrets.USER_NAME }}" >> $GITHUB_ENV
            echo "PASSWORD=${{ secrets.PASSWORD }}" >> $GITHUB_ENV

      - name: Build java-agent
        run: ./gradlew :java-apm-agent:java-agent:shadowJar

      - name: Build server
        run: ./gradlew :server:build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            java-agent/build/libs/*.jar
            server/build/libs/*.jar

  release:
    runs-on: self-hosted
    needs: build
    permissions:
      contents: write

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: List downloaded files
        run: ls -R

      - name: Create GitHub Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: |
            **/traffichunter-*.jar

  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
